# test_runner.py
import os

def check_ecori_presence():
    # The output file generated by main.py
    output_file = "Output.Fa"
    ecori_seq = "GAATTC"
    
    if not os.path.exists(output_file):
        print("Error: Output.Fa not found. Run main.py first.")
        return

    with open(output_file, 'r') as f:
        content = f.read().replace('\n', '')
    
    print(f"Testing {output_file} for EcoRI ({ecori_seq})...")
    
    if ecori_seq in content:
        print("FAILED: EcoRI site found in output plasmid!")
    else:
        print("PASSED: EcoRI site successfully removed/excluded.")

if __name__ == "__main__":
    check_ecori_presence()